// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjwKXasYuQMvHL0ENGxKQLOEX3r39sq58',
    appId: '1:1030784763715:web:02d8cd69ba798401d091f6',
    messagingSenderId: '1030784763715',
    projectId: 'eztajwid',
    authDomain: 'eztajwid.firebaseapp.com',
    storageBucket: 'eztajwid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_EHUzUHMi27qX78ADxKC5zeEyrGud3X8',
    appId: '1:1030784763715:android:dc2f869a3723151ad091f6',
    messagingSenderId: '1030784763715',
    projectId: 'eztajwid',
    storageBucket: 'eztajwid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Nq7awehAn2_Dh-cp55Ay8hRSYk0IG0I',
    appId: '1:1030784763715:ios:1b669e8b88e800cbd091f6',
    messagingSenderId: '1030784763715',
    projectId: 'eztajwid',
    storageBucket: 'eztajwid.appspot.com',
    iosBundleId: 'com.example.eztajwid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Nq7awehAn2_Dh-cp55Ay8hRSYk0IG0I',
    appId: '1:1030784763715:ios:ab938e04b07f603ad091f6',
    messagingSenderId: '1030784763715',
    projectId: 'eztajwid',
    storageBucket: 'eztajwid.appspot.com',
    iosBundleId: 'com.example.eztajwid.RunnerTests',
  );
}
